-- Primero elimina las tablas que dependen de otras
DROP TABLE CANCELACION CASCADE CONSTRAINTS;
DROP TABLE DESVIO CASCADE CONSTRAINTS;
DROP TABLE RETRASO CASCADE CONSTRAINTS;
DROP TABLE INCIDENCIA CASCADE CONSTRAINTS;
DROP TABLE VUELO CASCADE CONSTRAINTS;
DROP TABLE AVION CASCADE CONSTRAINTS;
DROP TABLE COMPAGNIA CASCADE CONSTRAINTS;
DROP TABLE AEROPUERTO CASCADE CONSTRAINTS;

-- Luego elimina las secuencias
DROP SEQUENCE secCancelacion;
DROP SEQUENCE secDesvio;
DROP SEQUENCE secRetraso;
DROP SEQUENCE secIncidencia;
DROP SEQUENCE secVuelo;
